name: carburapp
description: Application de recherche de stations-service avec suivi des visites
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI et navigation
  cupertino_icons: ^1.0.2

  # Carte et géolocalisation
  flutter_map: ^6.0.1
  latlong2: 0.9.1
  geolocator: ^10.1.0
  
  # Réseau
  http: ^1.1.0
  
  # Base de données locale - VERSION NATIVE FORCÉE
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Backend (Supabase) - VERSION COMPATIBLE
  supabase_flutter: ^1.10.25
  
  # Utilitaires
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# IMPORTANT: Forcer SQLite natif et bloquer sqflite_common_ffi
dependency_overrides:
  # Bloquer sqflite_common_ffi qui cause les problèmes
  sqflite_common_ffi: 2.3.0+4
  sqflite_common: 2.5.0+2
  # Forcer les bonnes versions
  ffi: ^2.0.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Configuration pour éviter les problèmes de polices
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: packages/flutter/fonts/Roboto-Regular.ttf
  #       - asset: packages/flutter/fonts/Roboto-Bold.ttf
  #         weight: 700